### ISSUE TITLE
Add to ESP Component Registry

### ISSUE THREAD

**Issue by manforowicz** [OpenCyphal/libcanard#227]
What do you think about adding libcanard to the [ESP Component Registry](https://components.espressif.com/)?
Since the ESP32 has great CAN bus support, having libcanard packaged in an ESP component would make it more accessible to developers.

Doing this would probably entail:
1. Requesting an OpenCyphal namespace through the [ESP Registry permissions](https://components.espressif.com/settings/permissions/) page. Giving key contributors access to this namespace.

2. Packaging up libcanard by following the [Packaging ESP-IDF Components](https://docs.espressif.com/projects/idf-component-manager/en/latest/guides/packaging_components.html) guide. This requires adding some metadata and build files.

3. Uploading the package to the ESP registry each time there's an update.

**Comment by pavel-kirienko** [comment]
Sounds interesting and I will support whatever activities are needed

**Comment by kumekay** [comment]
Hello @Manforowicz, I'm Sergei from Espressif, thank you so much for sending your request for namespace `opencyphal` in the ESP Component Registry. Since you are not an active contributor to the project, before approving your request, I decided to discuss the topic here.


@pavel-kirienko if you want a full control over components in the ESP Component Registry, could you please sign up here: https://components.espressif.com/users/login? Then you will be able to give permissions to other developers.

BTW, for ease of uploading I would highly recommend using our GitHub Action https://github.com/espressif/upload-components-ci-action 

@XDanielPaul FYI

**Comment by pavel-kirienko** [comment]
Thank you @kumekay for the advice. I have attempted to request the opencyphal namespace but it's already taken, presumably by @manforowicz. Could you please transfer it to me as the owner and then I will share access with the other team members? Thank you!

![image](https://github.com/user-attachments/assets/216392d5-3047-440f-a326-50b676b9052c)

**Comment by pavel-kirienko** [comment]
I also requested `cyphal` for security reasons.

**Comment by XDanielPaul** [comment]
Hello @pavel-kirienko, I'm Daniel from Espressif. 
I have approved your namespace request for the namespace `cyphal` and would further want to ask you to request the namespace `opencyphal` once again in the ESP Component Registry, it should be available now :)

**Comment by pavel-kirienko** [comment]
Thank you @XDanielPaul, this has been done.

@thirtytwobits FYI -- you don't seem to be registered in the ESP registry yet

**Comment by pavel-kirienko** [comment]
@manforowicz a pull request amending the GitHub actions pipelines as necessary would be accepted.

**Comment by XDanielPaul** [comment]
Thank you so much @pavel-kirienko, I have approved your namespace request for the `opencyphal` as well. You should be able to add other users now
